### ISSUE TITLE
Allow user to configure predefined dynamic timeExtent for the map view

### ISSUE THREAD

**Issue by matthiasstein** [conterra/mapapps-time-slider#3]
Use moment to provide this feature.

**Comment by matthiasstein** [comment]
Sample config:

```
"viewTimeExtent": {
                    "start": [
                        "2019-04-01T00:00Z",
                        {
                            "method": "substract",
                            "args": [
                                1,
                                "year"
                            ]
                        },
                        {
                            "method": "substract",
                            "args": [
                                1,
                                "months"
                            ]
                        }
                    ],
                    "end": "now"
```

**Comment by martinlohoff** [comment]
Goog new feature, thanks.

Is it possible to set start and stop like `"start": "current-year"` instead of now? We need to set the starting time extent to the current year plus 12 months (beginning of next year). Set the date statically is not an option.

**Comment by matthiasstein** [comment]
You can use this configuration:
```json
"viewTimeExtent": {
    "start": [
        {
            "method": "startOf",
            "args": [
                "year"
            ]
        }
    ],
    "end": [
        {
            "method": "endOf",
            "args": [
                "year"
            ]
        }
    ]
}
```

**Comment by matthiasstein** [comment]
Added in https://github.com/conterra/mapapps-time-slider/releases/tag/6.1.0

**Comment by martinlohoff** [comment]
Great that works. Is there any documentation about this? Is that just moment.js?

**Comment by matthiasstein** [comment]
You can use any moment.js manipulating-method (https://momentjs.com/docs/#/manipulating/) to create the start and end value.
The individual methods are configured via the array and thus called one after the other on the same moment object. It will start with an empty moment object (the current time). You can also use ISO string values as start value of the array.

**Comment by martinlohoff** [comment]
Ok, I think I've got this. Thanks.
